version: "3.8"

services:
  db:
    container_name: coding-review-db
    image: nouchka/sqlite3:latest
    volumes:
      - db:/root/db
    stdin_open: true
    tty: true

  app:
    container_name: coding-review-app
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - gems:/gems
    stdin_open: true
    tty: true

volumes:
  db:
  gems:
